[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "struphy"
version = "3.3.0"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Max Planck Institute for Plasma Physics" },
    { email = "stefan.possanner@ipp.mpg.de" },
    { email = "max.lindqvist@ipp.mpg.de" },
    { email = "eric.sonnendruecker@ipp.mpg.de" },
]
description = "Multi-model plasma physics package"
keywords = [
    "plasma physics, fusion, numerical modeling, partial differential equations, energetic particles",
]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy<=2.5.0",
    "cunumpy>=0.1.5, <=0.1.5",
    "pyccel>=2.2.0, <=2.2.3",
    "feectools >= 0.1.10, <=0.1.10",
    "scipy<=1.18.0",
    "h5py<=3.16.0",
    "matplotlib<=3.11.0",
    "pyyaml<=6.0.3",
    "vtk<=9.7.0",
    "tqdm<=4.70.0",
    "argcomplete<=3.7.0",
    "ipywidgets<=8.1.8",
    "plotly<=7.1.0",
    "pyvista<=0.49.0",
    "trame<=4.0.0",
    "trame-vtk<=2.11.8",
    "trame-vuetify<=3.2.2",
    "nest_asyncio2<=1.7.2",
    "vtk<=9.7.0",
    "pytest<=9.1.0",
    "pytest-mpi<=0.6",
    "pytest-testmon<=2.2.0",
    "ruff==0.15.0, <=0.16.0",
    "line_profiler<=5.0.2",
    "scope-profiler>=0.5.0, <=0.7.0",
]

[project.license]
file = "LICENSE"

[project.optional-dependencies]
mpi = [
    "mpi4py<=4.1.1",
]
phys = [
    "gvec>=1.1.0, <=1.5.0",
    "desc-opt<=0.17.1",
]
dev = [
    "struphy[mpi]",
    "notebook",
    "autopep8",
    "isort",
    "flake8",
    "pylint",
    "ssort",
    "add-trailing-comma",
    "pre-commit",
    "nbstripout",
    "tabulate",
    "tomli-w",
    "kaleido",
    "pandas",
    "scope-profiler[pproc]",
    "slurm-script-generator>=0.3.6",
]
doc = [
    "struphy[phys]",
    "jupyter",
    "nbconvert",
    "ipykernel",
    "sphinx",
    "sphinx-design",
    "lxml_html_clean",
    "sphinxcontrib-napoleon",
    "sphinx-copybutton",
    "sphinx-collections",
    "pydata-sphinx-theme",
    "nbsphinx",
    "m2r2",
    "myst-parser",
    "docutils",
    "ipyparallel",
    "scope-profiler[pproc]",
]
likwid = [
    "struphy[dev]",
    "pylikwid",
]
all = [
    "struphy[phys]",
    "struphy[dev]",
    "struphy[mpi]",
    "struphy[doc]",
    "struphy[likwid]",
]

[project.urls]
homepage = "https://struphy-hub.github.io/struphy/index.html"
documentation = "https://struphy-hub.github.io/struphy/index.html"
repository = "https://github.com/struphy-hub/struphy"
changelog = "https://github.com/struphy-hub/struphy/blob/devel/CHANGELOG.md"
"Bug Tracker" = "https://github.com/struphy-hub/struphy/issues"

[project.scripts]
struphy = "struphy.console.main:struphy"
kinetic-diagnostics = "struphy.diagnostics.console_diagn:main"

[tool.setuptools.package-data]
"struphy.fields_background.mhd_equil.eqdsk" = [
    "data/*.high",
]
"struphy.fields_background.mhd_equil.gvec" = [
    "run_01/*.dat",
    "run_01/*.ini",
    "run_02/*.dat",
    "run_02/*.ini",
    "run_03/*.dat",
    "run_03/*.ini",
    "run_03/*.nc",
]
struphy = [
    "compile_struphy.mk",
]

[tool.autopep8]
max_line_length = 120
ignore = [
    "E221,E226,E203,E265,E731,E711",
]

[tool.isort]
profile = "black"
line_length = 120

[tool.pylint]
max-line-length = 120

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "E265",
    "E402",
    "E701",
    "E722",
    "E731",
    "E741",
    "E742",
    "E743",
    "E902",
    "F401",
    "F403",
    "F405",
    "D211",
    "D213",
    "F841",
]

[tool.pytest.ini_options]
markers = [
    "models",
    "fluid",
    "kinetic",
    "hybrid",
    "single",
    "mpi_pic",
]
